MODEL_ID = "claude-haiku-4-5-20251001"
DISCOVERY_MODE = "serp" #deterministic | serp | api
DEBUG_MODE = True

EXTRACTION_MAX_TOKENS = 2048
STRATEGY_MAX_TOKENS = 2048
SERP_RESULT_LIMIT = 5
GROUNDHOG_MIN_DELAY_MS = 5000 
GROUNDHOG_MAX_TOKENS = 20000  # Max tokens for Groundhog responses
GROUNDHOG_BLOCK_PRIVATE_IPS = True
GROUNDHOG_USER_AGENT = "UA"
SECURITY_DELAY_MS = 0
MAX_CANDIDATES_PER_DIMENSION = 3

